### PR TITLE
XAI NN

### PR DESCRIPTION
**Pull request by SaraHoxha**
### Implementation of XAI for NN models.

This branch is based on rnn-keras, since i updated the tokenization method in that one to use keras tokenizer.

The rnn-keras PR should be approved first

Still **WIP**

### CODE REVIEW

**Comment by SaraHoxha** [comment]
@RafaelUrbina  should I put your utils file for XAI SVM into the general_utils folder?  Check this PR to see how I did it for NN This way we have better modularization. Lmk

@luispinto99  @naomiicm  lmk if you also agree with this modularization, if so i'll add the new path to ur files as well

**Comment by RafaelUrbina** [comment]
> @RafaelUrbina should I put your utils file for XAI SVM into the general_utils folder? Check this PR to see how I did it for NN This way we have better modularization. Lmk
 
R/ Yes please, that would be nice and better for readability

**Comment by SaraHoxha** [comment]
@RafaelUrbina  modularization of svm_utils done.
Also, please let's keep this PR as draft now since it's still WIP.
Thankss

**Comment by SaraHoxha** [comment]
Finished implementation & ran LIME for all NN models for both datasets. Everything looks ok to me. Lmk

**Pull request merged**
